"""Seed data generator — optional Phase 4.

Demo/dev only. Seed data is NOT part of the production schema build
pipeline: it's gated behind `--seed` on `scripts/build_schema.py`.

Design for scale (up to 1000 tables):

- Every entity table is seeded with exactly `rows_per_table` rows
  whose PKs are 1..rows_per_table. This is deterministic so FK
  generation never blocks on sibling calls — a child table's FK
  column can safely pick any integer in its parent's [1..N] range.
- Because there is no cross-table dependency, every entity-table
  call runs in parallel behind the same `asyncio.Semaphore` used
  by the Builder.
- Lookup tables are seeded deterministically from `allowed_values`
  in the schema.json — no LLM call needed.
- Junction tables are seeded deterministically with a handful of
  fixed pairings from the two parents' PK ranges.
- Each entity-table LLM call is wrapped in a validation feedback
  loop (wrong table name / row count → corrective re-prompt, max
  `_MAX_VALIDATION_ATTEMPTS` attempts). This mirrors the Builder so
  prompt drift is caught before it lands on disk.

Output: a single `<domain>_seed_data.sql` concatenating INSERTs in
`creation_order`, suitable for `psql -f` against a freshly created
schema.
"""

from __future__ import annotations

import asyncio
import json
import re
from dataclasses import dataclass
from pathlib import Path

import yaml
from anthropic import APIStatusError, AsyncAnthropic

from agentcore.architect.sql_text import read_paren_group, split_top_level
from agentcore.domain import DomainConfig

_MODEL = "claude-sonnet-4-6"
_MAX_TOKENS = 4096
_MAX_CONCURRENCY = 5
_SDK_MAX_RETRIES = 5
_MAX_VALIDATION_ATTEMPTS = 3

DEFAULT_ROWS_PER_TABLE = 10
DEFAULT_JUNCTION_ROWS = 5


_SYSTEM_PROMPT = """\
You are a test-data generator. You will be given one table's \
definition and must emit realistic INSERT statements for exactly \
`rows_per_table` rows.

RULES:
- Emit only SQL INSERT statements for the table named in `table.name`. \
No CREATE, no BEGIN, no prose, no markdown fences.
- Exactly `rows_per_table` INSERT statements. One row per INSERT.
- List column names explicitly. Do NOT insert the primary key or \
`created_at` — those are auto-generated by the database.
- For every foreign key column, pick an integer in the `parent_pk_range` \
given for that column (inclusive). Spread values across the range; \
don't use only 1.
- For value-set-typed columns (marked `allowed_values`), pick from that list.
- Respect NOT NULL and UNIQUE constraints — each UNIQUE column must be \
unique across the rows you emit.
- Use realistic, domain-appropriate values. Dates in 'YYYY-MM-DD' format. \
Strings single-quoted.
- Booleans MUST be the SQL literals TRUE or FALSE — never 0/1, never 'true'/'false'.
- Standard SQL only — no PostgreSQL-specific functions.

OUTPUT:
Return ONLY the INSERT statements, separated by newlines. No other text.
"""


@dataclass
class SeedResult:
    name: str
    ok: bool
    sql: str = ""
    error: str | None = None


_INSERT_HEAD_RE = re.compile(
    r"""INSERT\s+INTO\s+(?:"([^"]+)"|(\w+))""",
    re.IGNORECASE,
)


def _parse_inserts(sql: str) -> list[tuple[str, list[str], list[str]]]:
    """Parse every `INSERT INTO t (cols) VALUES (vals)` statement in `sql`.

    Returns (table_name, column_names, value_exprs) tuples. Handles
    parens and semicolons inside single-quoted strings via the shared
    `agentcore.sql_text` state machine — the old regex-based approach
    broke on realistic values like `'Smith (Jr.)'` or names with
    embedded `;`.

    Statements that fail to parse are skipped silently; the caller's
    INSERT-count check via `_INSERT_HEAD_RE` catches malformed output.
    """
    out: list[tuple[str, list[str], list[str]]] = []
    for head_match in _INSERT_HEAD_RE.finditer(sql):
        table = head_match.group(1) or head_match.group(2)
        i = head_match.end()
        while i < len(sql) and sql[i].isspace():
            i += 1
        if i >= len(sql) or sql[i] != "(":
            continue
        try:
            cols_body, i = read_paren_group(sql, i)
        except ValueError:
            continue
        m = re.match(r"\s*VALUES\s*", sql[i:], re.IGNORECASE)
        if not m:
            continue
        i += m.end()
        if i >= len(sql) or sql[i] != "(":
            continue
        try:
            vals_body, _ = read_paren_group(sql, i)
        except ValueError:
            continue
        cols = [c.strip() for c in cols_body.split(",")]
        vals = split_top_level(vals_body, ",")
        out.append((table, cols, vals))
    return out


# ── Deterministic seeders ────────────────────────────────────────────────────

def _seed_lookup_table(table: dict) -> str:
    """Emit INSERTs for a lookup table from its codes. The reconciler
    stores codes on value-set columns via `allowed_values`; for lookups
    themselves we inspect the table definition directly.
    """
    name = table["name"]
    # Lookup tables have fixed columns: code, label, sort_order, active.
    # We don't know the code list from the table alone — we infer it from
    # the value-set-typed columns that reference this lookup. The caller
    # resolves the code list and passes it in via `table["_seed_codes"]`.
    codes = table.get("_seed_codes") or []
    if not codes:
        return f"-- {name}: no codes found; skipping\n"

    lines = [f"-- {name}"]
    for idx, code in enumerate(codes, start=1):
        label = code.replace("_", " ").title()
        lines.append(
            f"INSERT INTO {name} (code, label, sort_order, active) "
            f"VALUES ('{code}', '{label}', {idx}, TRUE);"
        )
    return "\n".join(lines) + "\n"


def _collect_lookup_codes(schema: dict) -> dict[str, list[str]]:
    """Walk non-lookup tables, collect the `allowed_values` for every
    column that `references` a lookup table. Returns {lookup_name: [codes]}.
    """
    by_lookup: dict[str, list[str]] = {}
    for t in schema["tables"]:
        if t.get("lookup_table"):
            continue
        for col in t.get("columns") or []:
            ref = col.get("references") or {}
            lookup_name = ref.get("table")
            allowed = col.get("allowed_values")
            if lookup_name and allowed and lookup_name not in by_lookup:
                by_lookup[lookup_name] = list(allowed)
    return by_lookup


def _seed_junction_table(
    table: dict,
    rows_per_table: int,
    pair_count: int,
) -> str:
    """Emit a handful of fixed pairings for a junction table. Parent PKs
    are in 1..rows_per_table because every parent entity table is seeded
    with exactly that many rows.
    """
    name = table["name"]
    fks = table.get("foreign_keys") or []
    if len(fks) != 2:
        return f"-- {name}: skipping junction (expected 2 FKs, got {len(fks)})\n"

    col_a = fks[0]["column"]
    col_b = fks[1]["column"]

    lines = [f"-- {name}"]
    # Simple zig-zag pattern: (1,1), (1,2), (2,1), (2,2), ... — bounded by
    # pair_count and the available PK range.
    pairs: list[tuple[int, int]] = []
    for i in range(1, rows_per_table + 1):
        for j in range(1, rows_per_table + 1):
            pairs.append((i, j))
            if len(pairs) >= pair_count:
                break
        if len(pairs) >= pair_count:
            break

    for a, b in pairs:
        lines.append(
            f"INSERT INTO {name} ({col_a}, {col_b}) VALUES ({a}, {b});"
        )
    return "\n".join(lines) + "\n"


# ── Entity table seeder (LLM) ────────────────────────────────────────────────

def _build_entity_input(
    table: dict,
    parent_pk_ranges: dict[str, tuple[int, int]],
    rows_per_table: int,
) -> dict:
    """Assemble the user payload for one entity table's seed call."""
    fk_by_col = {fk["column"]: fk for fk in table.get("foreign_keys") or []}

    data_columns = []
    for col in table.get("columns") or []:
        entry = {
            "name": col["name"],
            "type": col["type"],
            "not_null": col.get("not_null", False),
            "unique": col.get("unique", False),
        }
        if col.get("allowed_values"):
            entry["allowed_values"] = list(col["allowed_values"])
        data_columns.append(entry)

    fk_columns = []
    for fk in table.get("foreign_keys") or []:
        low, high = parent_pk_ranges.get(
            fk["references_table"], (1, rows_per_table)
        )
        fk_columns.append({
            "name": fk["column"],
            "references_table": fk["references_table"],
            "parent_pk_range": [low, high],
        })

    return {
        "rows_per_table": rows_per_table,
        "table": {
            "name": table["name"],
            "primary_key": table.get("primary_key"),
            "comment": table.get("comment", ""),
            "data_columns": data_columns,
            "fk_columns": fk_columns,
        },
    }


def _validate_entity_sql(
    sql: str,
    expected_table: str,
    expected_rows: int,
    unique_columns: list[str] | None = None,
) -> list[str]:
    """Lightweight SQL-shape validator. Catches the common prompt drift
    cases: wrong table name, wrong row count, prose leaking through.
    Not a full SQL parser — the downstream psql load catches real
    syntax errors."""
    errors: list[str] = []
    stripped = sql.strip()
    if not stripped:
        return ["response is empty"]

    # Strip markdown fences if present.
    if stripped.startswith("```"):
        stripped = re.sub(r"^```[a-z]*\n?", "", stripped)
        stripped = re.sub(r"\n?```$", "", stripped)

    head_matches = list(_INSERT_HEAD_RE.finditer(stripped))
    if not head_matches:
        return [
            "response contains no INSERT statements (prose or wrong format?)"
        ]

    wrong_table = [
        m.group(1) or m.group(2)
        for m in head_matches
        if (m.group(1) or m.group(2)) != expected_table
    ]
    if wrong_table:
        errors.append(
            f"{len(wrong_table)} INSERT(s) target wrong table: "
            f"{sorted(set(wrong_table))}. Expected only '{expected_table}'."
        )

    if len(head_matches) != expected_rows:
        errors.append(
            f"expected exactly {expected_rows} INSERT statements, "
            f"got {len(head_matches)}"
        )

    if unique_columns:
        by_col: dict[str, list[str]] = {c: [] for c in unique_columns}
        for _table, cols, vals in _parse_inserts(stripped):
            if len(cols) != len(vals):
                continue
            for col, val in zip(cols, vals):
                if col in by_col:
                    by_col[col].append(val)
        for col, vals in by_col.items():
            dupes = {v for v in vals if vals.count(v) > 1}
            if dupes:
                errors.append(
                    f"UNIQUE column '{col}' has duplicate value(s): "
                    f"{sorted(dupes)}"
                )

    return errors


def _extract_sql(text: str) -> str:
    stripped = text.strip()
    if stripped.startswith("```"):
        stripped = re.sub(r"^```[a-z]*\n?", "", stripped)
        stripped = re.sub(r"\n?```$", "", stripped)
    return stripped.strip()


async def _call_entity(
    client: AsyncAnthropic,
    payload: dict,
    sem: asyncio.Semaphore,
    verbose: bool,
) -> str:
    """LLM call for one entity table with validation feedback loop."""
    user_message = yaml.safe_dump(
        payload, sort_keys=False, default_flow_style=False, allow_unicode=True
    )
    table_name = payload["table"]["name"]
    expected_rows = payload["rows_per_table"]
    unique_columns = [
        c["name"] for c in payload["table"]["data_columns"]
        if c.get("unique")
    ]

    messages: list[dict] = [{"role": "user", "content": user_message}]
    last_errors: list[str] = []

    async with sem:
        for attempt in range(_MAX_VALIDATION_ATTEMPTS):
            try:
                response = await client.messages.create(
                    model=_MODEL,
                    max_tokens=_MAX_TOKENS,
                    system=_SYSTEM_PROMPT,
                    messages=messages,
                )
            except APIStatusError as e:
                raise RuntimeError(f"LLM call failed: {e}") from e

            text = "".join(
                block.text for block in response.content
                if getattr(block, "type", None) == "text"
            )
            if verbose:
                usage = response.usage
                suffix = f" [attempt {attempt + 1}]" if attempt else ""
                print(
                    f"  seed [{table_name}] {usage.input_tokens} in / "
                    f"{usage.output_tokens} out{suffix}"
                )

            sql = _extract_sql(text)
            errors = _validate_entity_sql(
                sql, table_name, expected_rows, unique_columns
            )
            if not errors:
                return sql

            last_errors = errors
            if attempt == _MAX_VALIDATION_ATTEMPTS - 1:
                break
            if verbose:
                print(
                    f"  seed [{table_name}] validation failed "
                    f"({len(errors)} issue(s)) — re-prompting"
                )

            messages.append({"role": "assistant", "content": text})
            messages.append({
                "role": "user",
                "content": (
                    "Your previous response has the following issues:\n- "
                    + "\n- ".join(errors)
                    + f"\n\nReturn exactly {expected_rows} INSERT statements "
                    f"for the '{table_name}' table only. No prose, no fences."
                ),
            })

    raise RuntimeError(
        f"Seed failed for '{table_name}' after "
        f"{_MAX_VALIDATION_ATTEMPTS} attempts. Final issues: {last_errors}"
    )


# ── Public API ───────────────────────────────────────────────────────────────

async def seed_schema_async(
    domain: DomainConfig,
    schema: dict,
    api_key: str,
    *,
    rows_per_table: int = DEFAULT_ROWS_PER_TABLE,
    junction_rows: int = DEFAULT_JUNCTION_ROWS,
    client: AsyncAnthropic | None = None,
    concurrency: int = _MAX_CONCURRENCY,
    verbose: bool = True,
) -> tuple[str, list[SeedResult]]:
    """Generate seed SQL for every table in `schema`. Returns the full
    SQL text (ordered by `creation_order`) and one `SeedResult` per
    entity table.
    """
    owns_client = client is None
    if owns_client:
        client = AsyncAnthropic(api_key=api_key, max_retries=_SDK_MAX_RETRIES)

    tables_by_name = {t["name"]: t for t in schema["tables"]}
    lookup_codes = _collect_lookup_codes(schema)

    # Every entity table gets the same PK range. Parallel-safe.
    parent_pk_ranges: dict[str, tuple[int, int]] = {
        t["name"]: (1, rows_per_table)
        for t in schema["tables"]
        if not t.get("lookup_table")
        and (t.get("columns") or t.get("foreign_keys"))  # skip structural
    }

    # Classify tables.
    entity_tables: list[dict] = []
    lookup_tables: list[dict] = []
    junction_tables: list[dict] = []
    for t in schema["tables"]:
        if t.get("lookup_table"):
            t_copy = dict(t)
            t_copy["_seed_codes"] = lookup_codes.get(t["name"], [])
            lookup_tables.append(t_copy)
        elif (
            len(t.get("foreign_keys") or []) >= 2
            and not (t.get("columns") or [])
        ):
            junction_tables.append(t)
        else:
            entity_tables.append(t)

    sem = asyncio.Semaphore(concurrency)

    async def seed_one(table: dict) -> SeedResult:
        name = table["name"]
        try:
            payload = _build_entity_input(
                table, parent_pk_ranges, rows_per_table
            )
            sql = await _call_entity(client, payload, sem, verbose)
            return SeedResult(
                name=name, ok=True,
                sql=f"-- {name}\n{sql}\n",
            )
        except Exception as e:
            return SeedResult(name=name, ok=False, error=str(e))

    try:
        entity_results = await asyncio.gather(
            *(seed_one(t) for t in entity_tables)
        )
    finally:
        if owns_client:
            await client.close()

    # Assemble final SQL in creation order so FK references resolve.
    sql_by_table: dict[str, str] = {}
    for t in lookup_tables:
        sql_by_table[t["name"]] = _seed_lookup_table(t)
    for t in junction_tables:
        sql_by_table[t["name"]] = _seed_junction_table(
            t, rows_per_table, junction_rows
        )
    for r in entity_results:
        if r.ok:
            sql_by_table[r.name] = r.sql

    blocks: list[str] = [
        "-- Seed data generated by agentcore.seed_data",
        f"-- rows_per_table={rows_per_table} junction_rows={junction_rows}",
        "",
    ]
    for table_name in schema["creation_order"]:
        if table_name in sql_by_table:
            blocks.append(sql_by_table[table_name])

    full_sql = "\n".join(blocks)
    return full_sql, list(entity_results)


def seed_schema(
    domain: DomainConfig,
    schema: dict,
    api_key: str,
    *,
    rows_per_table: int = DEFAULT_ROWS_PER_TABLE,
    junction_rows: int = DEFAULT_JUNCTION_ROWS,
    client: AsyncAnthropic | None = None,
    concurrency: int = _MAX_CONCURRENCY,
    verbose: bool = True,
) -> tuple[str, list[SeedResult]]:
    """Synchronous wrapper for CLI use."""
    return asyncio.run(seed_schema_async(
        domain, schema, api_key,
        rows_per_table=rows_per_table,
        junction_rows=junction_rows,
        client=client,
        concurrency=concurrency,
        verbose=verbose,
    ))


def write_seed_file(domain: DomainConfig, sql: str) -> str:
    """Write seed SQL to the canonical location and return the filename."""
    seed_file = f"{domain.dir_name}_seed_data.sql"
    path = domain.generated_dir / seed_file
    path.write_text(sql, encoding="utf-8", newline="\n")
    return seed_file
